# Generated by Django 2.2.5 on 2019-09-26 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190926_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essays',
            name='essay_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 0, 6, 51, 247139), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 0, 6, 51, 189148), verbose_name='date published'),
        ),
    ]
