# Generated by Django 2.2.5 on 2019-09-27 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190927_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='occupation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essays',
            name='essay_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 15, 54, 54, 253146), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 15, 54, 54, 88990), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(),
        ),
    ]
