# Generated by Django 2.2.5 on 2020-01-28 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190927_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essays',
            name='essay_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 13, 51, 38, 200668), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 13, 51, 38, 26659), verbose_name='date published'),
        ),
    ]
