# Generated by Django 2.2.5 on 2020-01-28 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200128_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usernames',
        ),
        migrations.AlterField(
            model_name='essays',
            name='essay_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 13, 57, 39, 503821), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 13, 57, 39, 352541), verbose_name='date published'),
        ),
    ]
